---
# Base Packages

- name: install lists packages
  apt: pkg={{ item }} state=installed
  become: yes
  become_user: root

  with_items:
    - aptitude
    - git
    - git-core
    - git-flow
    - curl
    - wget
    - unzip
    - tar
    - gzip
    - bzip2
    

